src: add support for 12.3.1
bucharest-gold/node-rpm pull request #218
Opened 2019-05-22 21:02 UTC by lholmquist

2019-05-22 21:10 UTC, helio-frota approved these changes

2019-05-23 03:21 UTC, danbev requested changes
We need to update the patch version for Node.js. It looks like it is still 12.3.0?

2019-05-23 12:45 UTC, helio-frota requested changes
@danbev is right, I double checked only the embedded string.

2019-05-23 12:46 UTC, lholmquist commented
updated it

2019-05-23 12:48 UTC, danbev approved these changes

2019-05-23 13:39 UTC, helio-frota approved these changes

2019-05-23 14:26 UTC, merged